import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      fontFamily: {
        sans: ["'Inter'", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "monospace"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "surface-mint": {
          DEFAULT: "hsl(var(--surface-mint))",
          strong: "hsl(var(--surface-mint-strong))",
        },
        indigo: {
          deep: "hsl(var(--indigo-deep))",
        },
        "surface-lavender": {
          DEFAULT: "hsl(var(--surface-lavender))",
          soft: "hsl(var(--surface-lavender-soft))",
        },
        success: "hsl(var(--success))",
        warning: "hsl(var(--warning))",
        "warning-dark": "hsl(var(--warning-dark))",
        "warning-amber": "hsl(var(--warning-amber))",
        "surface-in-flight": "hsl(var(--surface-in-flight))",
        "surface-attention-soft": "hsl(var(--surface-attention-soft))",
        "surface-attention-urgent": "hsl(var(--surface-attention-urgent))",
        "surface-completed": "hsl(var(--surface-completed))",
        "surface-special": "hsl(var(--surface-special))",
        "tile-in-flight": "hsl(var(--tile-in-flight))",
        "tile-attention-soft": "hsl(var(--tile-attention-soft))",
        "tile-attention-urgent": "hsl(var(--tile-attention-urgent))",
        "tile-special": "hsl(var(--tile-special))",
        finery: {
          DEFAULT: "hsl(var(--finery-primary))",
          foreground: "hsl(var(--finery-primary-foreground))",
          accent: "hsl(var(--finery-accent))",
        },
        "washmen-aqua": "#02FFF7",
        "washmen-green": "#A4FF00",
        "washmen-orange": "#FF7D19",
        "washmen-pink": "#FF8CF9",
        "washmen-red": "#C83C3E",
        "washmen-teal": "#2EA692",
        "washmen-slate": "#585871",
        "washmen-cloudy": "#C3C8DB",
        "washmen-light-grey": "#EFEFF4",
        "washmen-stroke": "#F2F3F8",
        "washmen-bg": "#FAFBFC",
        "washmen-discount": "#F13578",
        "washmen-info": "#01A8CD",
        "washmen-express": "#9176FF",
        "washmen-express-light": "#E9E3FF",
        "washmen-light-blue": "#E1DEFB",
        "washmen-light-aqua": "#E5FFFE",
        "washmen-light-green": "#F3FFDD",
        "washmen-light-orange": "#FEF2DF",
        "washmen-light-pink": "#FFE8FE",
        "washmen-light-red": "#FBEEF2",
        "washmen-light-teal": "#D8FFF8",
        sidebar: {
          DEFAULT: "hsl(var(--background))",
          foreground: "hsl(var(--foreground))",
          primary: "hsl(var(--primary))",
          "primary-foreground": "hsl(var(--primary-foreground))",
          accent: "hsl(var(--accent))",
          "accent-foreground": "hsl(var(--accent-foreground))",
          border: "hsl(var(--border))",
          ring: "hsl(var(--ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
        "2xl": "calc(var(--radius) + 8px)",
        "3xl": "calc(var(--radius) + 16px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0", opacity: "0" },
          to: { height: "var(--radix-accordion-content-height)", opacity: "1" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)", opacity: "1" },
          to: { height: "0", opacity: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "progress-fill": {
          "0%": { width: "0%" },
          "100%": { width: "var(--progress-target, 50%)" },
        },
        "pulse-ring": {
          "0%": { boxShadow: "0 0 0 0 hsl(var(--accent) / 0.55)" },
          "70%": { boxShadow: "0 0 0 12px hsl(var(--accent) / 0)" },
          "100%": { boxShadow: "0 0 0 0 hsl(var(--accent) / 0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-6px)" },
        },
        sway: {
          "0%, 100%": { transform: "rotate(-4deg)" },
          "50%": { transform: "rotate(4deg)" },
        },
        "spin-slow": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "truck-roll": {
          "0%, 100%": { transform: "translateX(0)" },
          "50%": { transform: "translateX(6px)" },
        },
        shake: {
          "0%, 100%": { transform: "translateX(0)" },
          "20%, 60%": { transform: "translateX(-4px)" },
          "40%, 80%": { transform: "translateX(4px)" },
        },
        "bounce-soft": {
          "0%, 100%": { transform: "translateY(0) scale(1)" },
          "50%": { transform: "translateY(-4px) scale(1.04)" },
        },
        sparkle: {
          "0%, 100%": { opacity: "0.4", transform: "scale(0.9)" },
          "50%": { opacity: "1", transform: "scale(1.15)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.25s ease-out",
        "accordion-up": "accordion-up 0.25s ease-out",
        "fade-in": "fade-in 0.5s ease-out both",
        "scale-in": "scale-in 0.3s ease-out both",
        "progress-fill": "progress-fill 1.2s cubic-bezier(0.65, 0, 0.35, 1) 0.2s both",
        "pulse-ring": "pulse-ring 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        float: "float 4s ease-in-out infinite",
        sway: "sway 3s ease-in-out infinite",
        "spin-slow": "spin-slow 6s linear infinite",
        "truck-roll": "truck-roll 1.6s ease-in-out infinite",
        shake: "shake 0.6s ease-in-out",
        "bounce-soft": "bounce-soft 2s ease-in-out infinite",
        sparkle: "sparkle 1.8s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
